server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/navoiyazotlms}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:2702}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: ${DDL_AUTO:update}

exam:
  duration-minutes: ${EXAM_DURATION_MINUTES:60}
  question-count: ${EXAM_QUESTION_COUNT:40}
  max-attempts-per-candidate: ${EXAM_MAX_ATTEMPTS_PER_CANDIDATE:0}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
